### ISSUE TITLE
This cdn blew up :(

### ISSUE THREAD

**Issue by Chengyuan-artist** [ManiaciaChao/node-hustpass#7]
https://github.com/ManiaciaChao/node-hustpass/blob/b6b7805d8a4b7ea6f7b0ee3f97646bea46053cf9/captcha.ts#L28-L30

这个cdn炸了，导致 eng.traineddata 下下来是空的（，

换成原来的链接就可以了

```
 const worker = createWorker({
    langPath: "https://file-1252889006.cos.ap-guangzhou.myqcloud.com/tesseract",
  });
```

**Comment by ManiaciaChao** [comment]
从 https://github.com/ManiaciaChao/node-hustpass/commit/8b14c6c9a94a59543e90496b3c53853fef50e966 开始，`node-hustpass` 使用了 [winderica 的验证码识别](https://github.com/winderica/DailyReport/blob/master/src/utils/recognize.ts)，不再依赖Tesseract。

所以，不需要CDN了。
